<a href="https://colab.research.google.com/github/MichelaPascale/Challenges/blob/main/SecondaProvaChallenge/Notebook_preparazione.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv("Telco-Customer-Churn.partial.csv")

In [3]:
data

     Churn  customerID  ... MonthlyCharges  TotalCharges
0       No  4223-BKEOR  ...          64.85        1336.8
1       No  6035-RIIOM  ...          97.20       5129.45
2      Yes  3797-VTIDR  ...          23.45         23.45
3      Yes  2568-BRGYX  ...          70.20        237.95
4       No  2775-SEFEE  ...          61.90
...    ...         ...  ...            ...           ...
5629   Yes  0684-AOSIH  ...          95.00            95
5630    No  5982-PSMKW  ...          91.10        2198.3
5631    No  8044-BGWPI  ...          21.15        306.05
5632   Yes  7450-NWRTR  ...          99.45       1200.15
5633    No  4795-UXVCJ  ...          19.80         457.3

[5634 rows x 21 columns]

In [5]:
train, test = train_test_split(data,random_state=42,test_size=0.2)    # Suddivisione dei dati in training e test set

In [6]:
train

     Churn  customerID  ... MonthlyCharges  TotalCharges
4082    No  6729-FZWSY  ...          19.45       1195.95
1728    No  4806-DXQCE  ...         113.65       7714.65
2795    No  8690-ZVLCL  ...          88.00        6161.9
334     No  1530-ZTDOZ  ...          40.65       2070.75
3625    No  4006-HKYHO  ...          86.70        5309.5
...    ...         ...  ...            ...           ...
3772   Yes  1271-SJBGZ  ...          43.65        526.95
5191    No  5977-CKHON  ...          92.55          4039
5226    No  3635-JBPSG  ...          38.80           603
5390    No  4475-NVTLU  ...          19.20         903.7
860     No  2038-YSEZE  ...          67.45        1801.1

[4507 rows x 21 columns]

In [7]:
test

     Churn  customerID  ... MonthlyCharges  TotalCharges
2121    No  9501-UKKNL  ...          51.70        3005.8
915     No  0060-FUALY  ...          94.75       5597.65
2585   Yes  2951-QOQTK  ...          80.80        332.45
787    Yes  0337-CNPZE  ...         106.30       4443.45
101     No  5862-BRIXZ  ...          60.75        2893.4
...    ...         ...  ...            ...           ...
4416    No  5345-BMKWB  ...          20.25        158.35
1954    No  6217-TOWGS  ...          75.40       1322.55
1616   Yes  3325-FUYCG  ...         106.10        2847.4
3807    No  4717-GHADL  ...          79.60        4024.2
322    Yes  8806-EAGWC  ...          55.15        159.15

[1127 rows x 21 columns]

In [8]:
train.to_csv('train.csv', index=False)
test.to_csv('test.csv', index=False)